<table id="protocols_table" class="tablesorter">
    <thead>
        <tr>
            <th>Protocol</th>
            <th>Author</th>
            <th>Version</th>
            <th>Community</th>
            <th>Played</th>
            <th>Downloaded</th>
            <th>Reviews</th>
            <th>Status</th>
            <th>Operations</th>
        </tr>
    </thead>
    <tbody>
        <c:forEach var="protocol" items="${protocols}">
            <tr>
                <td>${protocol.name}</td>
                <td>${protocol.authorName}</td>
                <td>0</td>
                <td>0</td>
                <td>${protocol.timePlayed}</td>
                <td>0</td>
                <td>0</td>
                <td>${protocol.status}</td>
                <td>TBD</td>
            </tr>
        </c:forEach>
    </tbody>
</table>